/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Classes.Departamento;
import Classes.Funcionario;
import Conexao.ServicoBancoFuncionario;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author lipeg
 */
public class TelaFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form TelaFuncionario
     */
    public TelaFuncionario() {
        initComponents();
    }
    
    TelaConsultaDepartamento telaConsultaDepartamento;
    ServicoBancoFuncionario srvFuc = new ServicoBancoFuncionario();
    SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
    Funcionario fun;
    
    
    private void limparTela(){
        jComboFuncionario.setSelectedIndex(-1);
        jtNome.setText("");
        jCodigoDepartamento.setText("");
        jtCpf.setText("");
        jtRg.setText("");
        jtData.setText("");
        jtNome.requestFocus();
        jLimpar.setEnabled(true);
        
        
    }
    
    
    public void carregarComboBoxDepartamento() throws SQLException{
        try {
            if (jComboFuncionario.getItemCount() > 0){
               jComboFuncionario.removeAllItems();
            }
        
          ArrayList<Funcionario> lista = srvFuc.getFuncionarioByLista();
          
          for (Funcionario u:lista){
            jComboFuncionario.addItem(u);
          }      
        
          this.limparTela();
          
        } catch (SQLException ex) {
            Logger.getLogger(TelaFuncionario.class.getName()).log(Level.SEVERE, null, ex);
          };        
    
        
        
    }
    
    private void atualizarListaFuncionario(){
        try {
            if (jComboFuncionario.getItemCount() > 0){
               jComboFuncionario.removeAllItems();
            }
        
          ArrayList<Funcionario> lista = srvFuc.getFuncionarioByLista();
          
          for (Funcionario u:lista){
            jComboFuncionario.addItem(u);
          }      
        
          this.limparTela();
          
        } catch (SQLException ex) {
             Logger.getLogger(TelaFuncionario.class.getName()).log(Level.SEVERE, null, ex);
          }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboFuncionario = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jtCpf = new javax.swing.JTextField();
        jtRg = new javax.swing.JTextField();
        jtData = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLimpar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jCodigoDepartamento = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jComboFuncionario.setModel(new javax.swing.DefaultComboBoxModel<>(new Funcionario[] {fun}));
        jComboFuncionario.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboFuncionarioItemStateChanged(evt);
            }
        });

        jLabel1.setText("Selecionar Funcionario: ");

        jLabel2.setText("Cadastrar Funcionario");

        jtRg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtRgActionPerformed(evt);
            }
        });

        jLabel3.setText("Nome:");

        jLabel4.setText("CPF:");

        jLabel5.setText("RG:");

        jLabel6.setText("Data Nascimento:");

        jButton1.setText("Salvar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLimpar.setText("Limpa");
        jLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLimparMouseClicked(evt);
            }
        });

        jButton3.setText("Cancelar/Sair");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jLabel7.setText("Selecione ocódigo do departamento");

        jButton2.setText("Tabela de Departamento");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        btExcluir.setText("Excluir");
        btExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btExcluirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(0, 24, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(41, 41, 41)
                        .addComponent(btExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2)
                                .addComponent(jComboFuncionario, 0, 234, Short.MAX_VALUE)
                                .addComponent(jtNome)
                                .addComponent(jtCpf)
                                .addComponent(jtRg)
                                .addComponent(jtData))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCodigoDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jButton2)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jCodigoDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLimpar)
                    .addComponent(jButton3)
                    .addComponent(btExcluir))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtRgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtRgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtRgActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        dispose();
    }//GEN-LAST:event_jButton3MouseClicked

    private void jLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLimparMouseClicked
        this.limparTela();
    }//GEN-LAST:event_jLimparMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        if (jtNome.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Informe o nome do funcionario!");
            jtNome.requestFocus();
            return;
        }
        
        if (jtCpf.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Informe o cpf!");
            jtCpf.requestFocus();
            return;
        }

        if (jtRg.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Informe o RG!");
            jtRg.requestFocus();
            return;
        }
        
        if (jtData.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Informe a data de nascimento!");
            jtData.requestFocus();
            return;
        }
        
        if (jCodigoDepartamento.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Informe o Código do Departamento!");
            jCodigoDepartamento.requestFocus();
            return;
        }
        
       try {
        if (jComboFuncionario.getSelectedIndex() >= 0){ //alterar
            Funcionario funcionario = (Funcionario) jComboFuncionario.getSelectedItem();
            funcionario.setIdDepartamento(Integer.parseInt(jCodigoDepartamento.getText()));
            funcionario.setNome(jtNome.getText());
            funcionario.setCpf(jtCpf.getText());
            funcionario.setRg(jtRg.getText());
            funcionario.setDataNascimento(formato.parse(jtData.getText()));
            srvFuc.update(funcionario);
        }
        else { //gravar
               Funcionario funcionario = new Funcionario(Integer.parseInt(jCodigoDepartamento.getText()),jtNome.getText(), jtCpf.getText(), jtRg.getText(), formato.parse(jtData.getText()));
               srvFuc.insert(funcionario);
             }
          
        this.atualizarListaFuncionario();
          
        } catch (SQLException ex) {
            
        } catch (ParseException ex) {
            Logger.getLogger(TelaFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jComboFuncionarioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboFuncionarioItemStateChanged
        if (jComboFuncionario.getItemCount() <= 0){
            return;
        }
        
        if (jComboFuncionario.getSelectedIndex() < 0){
            return;
        } 
        
        Funcionario funcionario = (Funcionario) jComboFuncionario.getSelectedItem();
        jCodigoDepartamento.getText();
        jtNome.setText(funcionario.getNome());
        jtCpf.setText(funcionario.getCpf());
        jtRg.setText(funcionario.getRg());
        jtData.setText(formato.format(funcionario.getDataNascimento()));
        
        jLimpar.setEnabled(true);
    }//GEN-LAST:event_jComboFuncionarioItemStateChanged

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.atualizarListaFuncionario();
    }//GEN-LAST:event_formWindowActivated

    private void btExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btExcluirMouseClicked
        if (jComboFuncionario.getSelectedIndex() < 0)
            return;
        
        //resp--> 0 = yes 1 = no 2 = cancel
        int resp = JOptionPane.showConfirmDialog(null, "Excluir registro?");
        if (resp == 0){
            try {
                srvFuc.delete((Funcionario) jComboFuncionario.getSelectedItem());
                
                this.atualizarListaFuncionario();
            } catch (SQLException ex) {
                Logger.getLogger(TelaFuncionario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btExcluirMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        if (telaConsultaDepartamento == null){
           
           telaConsultaDepartamento = new TelaConsultaDepartamento();
           }
           telaConsultaDepartamento.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JTextField jCodigoDepartamento;
    private javax.swing.JComboBox<Funcionario> jComboFuncionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jLimpar;
    private javax.swing.JTextField jtCpf;
    private javax.swing.JTextField jtData;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtRg;
    // End of variables declaration//GEN-END:variables
}
