/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Classes.Departamento;
import Classes.Funcionario;
import Conexao.ServicoBancoFuncionario;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author lipeg
 */
public class TelaFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form TelaFuncionario
     */
    public TelaFuncionario() {
        initComponents();
    }
    
    TelaConsultaDepartamento telaConsultaDepartamento;
    ServicoBancoFuncionario srvFuc = new ServicoBancoFuncionario();
    SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
    Funcionario fun;
    
    
    private void limparTela(){
        jComboFuncionario.setSelectedIndex(-1);
        jtNome.setText("");
        jCodigoDepartamento.setText("");
        jtCpf.setText("");
        jtRg.setText("");
        jtData.setText("");
        jtNome.requestFocus();
        jLimpar.setEnabled(true);
        
        
    }
    
    
    public void carregarComboBoxDepartamento() throws SQLException{
        try {
            if (jComboFuncionario.getItemCount() > 0){
               jComboFuncionario.removeAllItems();
            }
        
          ArrayList<Funcionario> lista = srvFuc.getFuncionarioByLista();
          
          for (Funcionario u:lista){
            jComboFuncionario.addItem(u);
          }      
        
          this.limparTela();
          
        } catch (SQLException ex) {
            Logger.getLogger(TelaFuncionario.class.getName()).log(Level.SEVERE, null, ex);
          };        
    
        
        
    }
    
    private void atualizarListaFuncionario(){
        try {
            if (jComboFuncionario.getItemCount() > 0){
               jComboFuncionario.removeAllItems();
            }
        
          ArrayList<Funcionario> lista = srvFuc.getFuncionarioByLista();
          
          for (Funcionario u:lista){
            jComboFuncionario.addItem(u);
          }      
        
          this.limparTela();
          
        } catch (SQLException ex) {
             Logger.getLogger(TelaFuncionario.class.getName()).log(Level.SEVERE, null, ex);
          }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboFuncionario = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jtCpf = new javax.swing.JTextField();
        jtRg = new javax.swing.JTextField();
        jtData = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLimpar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jCodigoDepartamento = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboFuncionario.setModel(new javax.swing.DefaultComboBoxModel<>(new Funcionario[] {fun}));
        jComboFuncionario.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboFuncionarioItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 45, 234, -1));

        jLabel1.setText("Selecionar Funcionario: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 48, 195, -1));

        jLabel2.setText("Cadastrar Funcionario");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 11, -1, -1));
        getContentPane().add(jtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 83, 234, -1));
        getContentPane().add(jtCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 121, 234, -1));

        jtRg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtRgActionPerformed(evt);
            }
        });
        getContentPane().add(jtRg, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 159, 234, -1));
        getContentPane().add(jtData, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 197, 234, -1));

        jLabel3.setText("Nome:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 86, -1, -1));

        jLabel4.setText("CPF:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 124, -1, -1));

        jLabel5.setText("RG:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 162, -1, -1));

        jLabel6.setText("Data Nascimento:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 200, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 255, 255));
        jButton1.setText("Salvar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 302, -1, -1));

        jLimpar.setBackground(new java.awt.Color(0, 255, 255));
        jLimpar.setText("Limpa");
        jLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLimparMouseClicked(evt);
            }
        });
        getContentPane().add(jLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 302, -1, -1));

        jButton3.setBackground(new java.awt.Color(0, 255, 255));
        jButton3.setText("Cancelar/Sair");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 302, -1, -1));

        jLabel7.setText("Selecione ocódigo do departamento");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 239, -1, -1));
        getContentPane().add(jCodigoDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 236, 36, -1));

        jButton2.setBackground(new java.awt.Color(0, 255, 255));
        jButton2.setText("Tabela de Departamento");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 235, -1, -1));

        btExcluir.setBackground(new java.awt.Color(0, 255, 255));
        btExcluir.setText("Excluir");
        btExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btExcluirMouseClicked(evt);
            }
        });
        getContentPane().add(btExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 302, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Degrade-Radial-1024x576.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-230, -50, 710, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtRgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtRgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtRgActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        dispose();
    }//GEN-LAST:event_jButton3MouseClicked

    private void jLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLimparMouseClicked
        this.limparTela();
    }//GEN-LAST:event_jLimparMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        if (jtNome.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Informe o nome do funcionario!");
            jtNome.requestFocus();
            return;
        }
        
        if (jtCpf.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Informe o cpf!");
            jtCpf.requestFocus();
            return;
        }

        if (jtRg.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Informe o RG!");
            jtRg.requestFocus();
            return;
        }
        
        if (jtData.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Informe a data de nascimento!");
            jtData.requestFocus();
            return;
        }
        
        if (jCodigoDepartamento.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Informe o Código do Departamento!");
            jCodigoDepartamento.requestFocus();
            return;
        }
        
       try {
        if (jComboFuncionario.getSelectedIndex() >= 0){ //alterar
            Funcionario funcionario = (Funcionario) jComboFuncionario.getSelectedItem();
            
            funcionario.setNome(jtNome.getText());
            funcionario.setCpf(jtCpf.getText());
            funcionario.setRg(jtRg.getText());
            funcionario.setDataNascimento(formato.parse(jtData.getText()));
            funcionario.setIdDepartamento(Integer.parseInt(jCodigoDepartamento.getText()));
            srvFuc.update(funcionario);
           
        }
        else { //gravar
               Funcionario funcionario = new Funcionario(Integer.parseInt(jCodigoDepartamento.getText()),jtNome.getText(), jtCpf.getText(), jtRg.getText(), formato.parse(jtData.getText()));
               srvFuc.insert(funcionario);
               limparTela();
               
             }
          limparTela();
        this.atualizarListaFuncionario();
          
        } catch (SQLException ex) {
            
        } catch (ParseException ex) {
            Logger.getLogger(TelaFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jComboFuncionarioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboFuncionarioItemStateChanged
        if (jComboFuncionario.getItemCount() <= 0){
            return;
        }
        
        if (jComboFuncionario.getSelectedIndex() < 0){
            return;
        } 
        
        Funcionario funcionario = (Funcionario) jComboFuncionario.getSelectedItem();
        jCodigoDepartamento.getText();
        jtNome.setText(funcionario.getNome());
        jtCpf.setText(funcionario.getCpf());
        jtRg.setText(funcionario.getRg());
        jtData.setText(formato.format(funcionario.getDataNascimento()));
        
        jLimpar.setEnabled(true);
    }//GEN-LAST:event_jComboFuncionarioItemStateChanged

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.atualizarListaFuncionario();
    }//GEN-LAST:event_formWindowActivated

    private void btExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btExcluirMouseClicked
        if (jComboFuncionario.getSelectedIndex() < 0)
            return;
        
        //resp--> 0 = yes 1 = no 2 = cancel
        int resp = JOptionPane.showConfirmDialog(null, "Excluir registro?");
        if (resp == 0){
            try {
                srvFuc.delete((Funcionario) jComboFuncionario.getSelectedItem());
                
                this.atualizarListaFuncionario();
            } catch (SQLException ex) {
                Logger.getLogger(TelaFuncionario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btExcluirMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        if (telaConsultaDepartamento == null){
           
           telaConsultaDepartamento = new TelaConsultaDepartamento();
           }
           telaConsultaDepartamento.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JTextField jCodigoDepartamento;
    private javax.swing.JComboBox<Funcionario> jComboFuncionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton jLimpar;
    private javax.swing.JTextField jtCpf;
    private javax.swing.JTextField jtData;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtRg;
    // End of variables declaration//GEN-END:variables
}
