/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Classes.Departamento;
import Classes.Funcionario;
import Conexao.ServicoBancoDepartamento;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author lipeg
 */
public class TelaDepartamento extends javax.swing.JFrame {

    /**
     * Creates new form TelaDepartamento
     */
    public TelaDepartamento() {
        initComponents();
    }
    ServicoBancoDepartamento srvDep = new ServicoBancoDepartamento();
    Departamento dep;
    
    
     private void limparTela(){
        jComboBox1.setSelectedIndex(-1);
        jNomeDepartamento.setText("");
        
        
        
    }
     
       public void carregarComboBoxDepartamento() throws SQLException{
        try {
            if (jComboBox1.getItemCount() > 0){
               jComboBox1.removeAllItems();
            }
        
          ArrayList<Departamento> lista = srvDep.getDepartamentoByLista();
          
          for (Departamento u:lista){
            jComboBox1.addItem(u);
          }      
        
          this.limparTela();
          
        } catch (SQLException ex) {
            Logger.getLogger(TelaFuncionario.class.getName()).log(Level.SEVERE, null, ex);
          };        
    
        
        
    }
    
    
     private void atualizarListaDepartamento(){
        try {
            if (jComboBox1.getItemCount() > 0){
               jComboBox1.removeAllItems();
            }
        
          ArrayList<Departamento> lista = srvDep.getDepartamentoByLista();
          
          for (Departamento u:lista){
            jComboBox1.addItem(u);
          }      
        
          this.limparTela();
          
        } catch (SQLException ex) {
             Logger.getLogger(TelaFuncionario.class.getName()).log(Level.SEVERE, null, ex);
          }        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jNomeDepartamento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btSalvar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new Departamento[] {dep}));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 48, 234, -1));

        jLabel1.setText("Cadastro Departamentos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 11, -1, -1));

        jLabel2.setText("Selecionar Departamento");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 51, -1, -1));
        getContentPane().add(jNomeDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 86, 234, -1));

        jLabel3.setText("Nome do Departamneto:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 89, -1, -1));

        btSalvar.setBackground(new java.awt.Color(0, 255, 255));
        btSalvar.setText("Salvar");
        btSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btSalvarMouseClicked(evt);
            }
        });
        getContentPane().add(btSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 120, -1, -1));

        btExcluir.setBackground(new java.awt.Color(0, 255, 255));
        btExcluir.setText("Excluir");
        btExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btExcluirMouseClicked(evt);
            }
        });
        getContentPane().add(btExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 120, -1, -1));

        btSair.setBackground(new java.awt.Color(0, 255, 255));
        btSair.setText("Sair");
        btSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btSairMouseClicked(evt);
            }
        });
        getContentPane().add(btSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 120, -1, -1));

        btLimpar.setBackground(new java.awt.Color(0, 255, 255));
        btLimpar.setText("Limpar");
        btLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btLimparMouseClicked(evt);
            }
        });
        getContentPane().add(btLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 120, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Degrade-Radial-1024x576.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-260, -60, 770, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSairMouseClicked
        dispose();
    }//GEN-LAST:event_btSairMouseClicked

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
         if (jComboBox1.getItemCount() <= 0){
            return;
        }
        
        if (jComboBox1.getSelectedIndex() < 0){
            return;
        } 
        
        Departamento departamento = (Departamento) jComboBox1.getSelectedItem();
        
        jNomeDepartamento.setText(departamento.getNomeDepartamento());
        
      
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void btSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSalvarMouseClicked
        if (jNomeDepartamento.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Informe o Nome do Departamento!");
            jNomeDepartamento.requestFocus();
            return;
        }
        
       try {
        if (jComboBox1.getSelectedIndex() >= 0){ //alterar
            Departamento departamento = (Departamento) jComboBox1.getSelectedItem();
            departamento.setNomeDepartamento(jNomeDepartamento.getText());
            srvDep.update(departamento);
        }
        else { //gravar
               Departamento departamento = new Departamento(jNomeDepartamento.getText());
               srvDep.insert(departamento);
             }
         
        limparTela();
        this.atualizarListaDepartamento();
          
        } catch (SQLException ex) {
            
        }
    }//GEN-LAST:event_btSalvarMouseClicked

    private void btExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btExcluirMouseClicked
         if (jComboBox1.getSelectedIndex() < 0)
            return;
        
        //resp--> 0 = yes 1 = no 2 = cancel
        int resp = JOptionPane.showConfirmDialog(null, "Excluir registro?");
        if (resp == 0){
            try {
                srvDep.delete((Departamento) jComboBox1.getSelectedItem());
                
                this.atualizarListaDepartamento();
            } catch (SQLException ex) {
                Logger.getLogger(TelaFuncionario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btExcluirMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        atualizarListaDepartamento();
    }//GEN-LAST:event_formWindowActivated

    private void btLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLimparMouseClicked
        limparTela();
    }//GEN-LAST:event_btLimparMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDepartamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btSalvar;
    private javax.swing.JComboBox<Departamento> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jNomeDepartamento;
    // End of variables declaration//GEN-END:variables
}
